### ISSUE TITLE
isDirectoryExists method creates directory instead of just checking up

### ISSUE THREAD

**Issue by artemtrofimov** [snatik/android-storage#10] opened 2015-04-05 07:54 UTC
**What you should do to reproduce the bug**
`Storage storage = SimpleStorage.getInternalStorage(context);
Log.e("1",  "does " + DIR_PATH + " exist " + storage.isDirectoryExists(DIR_PATH);`
Always returns `true`, because this method actually creates the dir.

**Why does this happen?**
AbstractDiskStorage invokes `buildPath(name)` inside `isDirectoryExists(String name)`.
`buildPath(name)` has `context.getDir(directoryName, Context.MODE_PRIVATE)` in InternalStorage implementation. 
`getDir` method creates the dir if it does not already exist.

**Comment by sukisoft** [comment] 2016-05-24 14:09
I was facing this issue, too. But for me, this happens also when you are using the ExternalStorage.

Further more i was facing major bugs / problems with the createDirectory() methods as well. They seem to create "shallow" folders, only via TotalCommander i was able to find them within the directory structure.

To get a workaround on this, i ended up NOT using the isDirectoryExists / createDirectory methods, but the simple File.mkdir() method.

This is pretty odd, though... because this lib was designed to get a way around the File handling and such...

**Comment by sromku** [comment] 2017-07-01 10:24
You are totally right and it's a bug. Fixed in latest version.

**Closed by sromku** 2017-07-01 10:24 UTC
Labels: bug
